name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean verify
      
    - name: Verify JAR was created
      run: |
        if [ ! -f target/PerPlayerKit-*.jar ]; then
          echo "Build failed - JAR file not found!"
          exit 1
        fi
        echo "Build successful - JAR created:"
        ls -la target/PerPlayerKit-*.jar
